name: Run tests

on:
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - name: Bun test
        with:
          bun-version: latest
      - run: bun test --coverage
